# config/manual_pairs.py
MANUAL_PAIRS = [
    "BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT",
    "ADAUSDT","DOGEUSDT","MATICUSDT","LINKUSDT","LTCUSDT",
    "DOTUSDT","AVAXUSDT","UNIUSDT","BCHUSDT","TRXUSDT",
    "ALGOUSDT","ATOMUSDT","XLMUSDT","NEARUSDT","VETUSDT",
    "APEUSDT","FILUSDT","SANDUSDT","MANAUSDT","ICPUSDT",
    "EOSUSDT","AAVEUSDT","THETAUSDT","PEPEUSDT"
]
